name:                skip-var
version:             0.1.1.0
github:              "dtaskoff/skip-var"
license:             MIT
license-file:        LICENSE
author:              "Daniel Taskoff <daniel.taskoff@gmail.com>, Georgi Lyubenov <godzbanebane@gmail.com>"
maintainer:          "Daniel Taskoff <daniel.taskoff@gmail.com>, Georgi Lyubenov <godzbanebane@gmail.com>"
stability:           "experimental"
copyright:           "2018 (c) Daniel Taskoff, 2018 (c) Georgi Lyubenov"

extra-source-files:
- CHANGELOG.md
- README.md

synopsis:            Skip variables
category:            Concurrency

description:         Please see the README on GitHub at <https://github.com/dtaskoff/skip-var#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -fwarn-incomplete-uni-patterns
  - -fwarn-incomplete-record-updates
